# This is a sample plugin.yml
# For more information refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.jderbysh.MinedGames.MinedGames
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  message:
    description: set the sample message
    usage: /<command>
    permission: message
  score:
    description: display a players current score
    usage: /<command>
  join:
    description: puts a player in the upcoming MinedGame.
    usage: /<command>
  start:
    description: starts the upcoming Mined Game
    usage: /<command>
  lobby:
    description: creates a lobby for a Mined Game.  Lets players start a Mined Game.
    usage: /<command>
  trade:
    description: Lets you trade 50 of your hard-earned points for an axe, shovel, or pick.
    usage: /<command> tool
permissions:
  message:
    description: gives permission to change the welcome message
    default: op
  score:
    description: gives separate permission to use the score command.  
    default: true
  join:
    description: allows a player to join a MinedGames GAME.
    default: true
  start:
    description: allows a player to start a MinedGame
    default: true
  lobby:
    description: allows a player to create a MinedGame in waiting.
    default: true
  trade:
    description: allows a player to trade points for tools during a game.
    default: true